version: '3.7'

services:
  currency-exchange:
    image: nikkscode/currency-exchange-service:v0.0.2
    deploy:
      resources:
        limits:
          memory: 700m
    ports:
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka

  naming-server:
    image: nikkscode/naming-server:v0.0.1
    deploy:
      resources:
        limits:
          memory: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network

networks:
  currency-network:
