name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Api-Gatway Docker image
      run: docker build --tag api-gateway:$(date +%s) -f Dockerfile /api-gateway/Dockerfile 
    - name: Build the currency-conversion-service Docker Image
      run: docker build ./currency-conversion-service --file Dockerfile --tag api-gateway:$(date +%s)
    - name: Build the currency-exchange-service Docker Image
      run: docker build ./currency-exchange-service --file Dockerfile --tag api-gateway:$(date +%s)
    - name: Build the naming-server Docker Image
      run: docker build ./naming-server --file Dockerfile --tag api-gateway:$(date +%s)
